name       : python-cryptography
version    : 2.1.4
release    : 7
source     :
    - https://files.pythonhosted.org/packages/source/c/cryptography/cryptography-2.1.4.tar.gz : e4d967371c5b6b2e67855066471d844c5d52d210c36c28d49a8507b96e2c5291
license    : Apache-2.0
component  : programming.python
summary    : A package designed to expose cryptographic recipes and primitives to Python developers
description: |
    A package designed to expose cryptographic recipes and primitives to Python developers
builddeps  :
    - pkgconfig(python-3.5)
    - python-cffi
    - python-setuptools
rundeps    :
    - python-asn1
    - python-asn1crypto
    - python-cffi
    - python-enum34
    - python-idna
    - python-ipaddress
    - python-packaging
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
