name       : python-cryptography
version    : 1.8.1
release    : 4
source     :
    - https://pypi.python.org/packages/ec/5f/d5bc241d06665eed93cd8d3aa7198024ce7833af7a67f6dc92df94e00588/cryptography-1.8.1.tar.gz : 323524312bb467565ebca7e50c8ae5e9674e544951d28a2904a50012a8828190
license    : Apache-2.0
component  : programming.python
summary    : A package designed to expose cryptographic recipes and primitives to Python developers
description: |
    A package designed to expose cryptographic recipes and primitives to Python developers
builddeps  :
    - pkgconfig(python-3.5)
    - python-cffi
    - python-cparser
    - python-setuptools
rundeps    :
    - python-asn1
    - python-asn1crypto
    - python-cffi
    - python-cparser
    - python-enum34
    - python-idna
    - python-ipaddr
    - python-packaging
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
