name       : python-cryptography
version    : 41.0.3
release    : 25
source     :
    - https://pypi.io/packages/source/c/cryptography/cryptography-41.0.3.tar.gz : 6d192741113ef5e30d89dcb5b956ef4e1578f304708701b8b73d38e3e1461f34
homepage   : https://github.com/pyca/cryptography
license    : Apache-2.0
component  : programming.python
networking : yes
summary    : A package designed to expose cryptographic recipes and primitives to Python developers
description: |
    A package designed to expose cryptographic recipes and primitives to Python developers.
builddeps  :
    - pkgconfig(python3)
    - cargo
    - python-cffi
    - python-setuptools-rust
    - python-cryptography-vectors # check, update this package whenever you update python-cryptography
    - python-hypothesis           # check
    - python-iso8601              # check
    - python-pretend              # check
    - python-pytest-benchmark     # check
    - pytest-runner               # check
    - pytest-subtests             # check
    - python-pytz                 # check
rundeps    :
    - python-cffi
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest
