name       : python-cryptography
version    : 2.1.2
release    : 6
source     :
    - https://github.com/pyca/cryptography/archive/2.1.2.tar.gz : 88af6f06d332696002ab89eb86eec5d809458a1f9634cf9a4fb7ef34a80b312d
license    : Apache-2.0
component  : programming.python
summary    : A package designed to expose cryptographic recipes and primitives to Python developers
description: |
    A package designed to expose cryptographic recipes and primitives to Python developers
builddeps  :
    - pkgconfig(python-3.5)
    - python-cffi
    - python-setuptools
rundeps    :
    - python-asn1
    - python-asn1crypto
    - python-cffi
    - python-enum34
    - python-idna
    - python-ipaddr
    - python-packaging
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
