name       : python-cryptography
version    : '2.7'
release    : 13
source     :
    - https://github.com/pyca/cryptography/archive/2.7.tar.gz : 6e01aafcd430086f1a943dcf04d71cfc2247aedeec5d6c474ce5450acd2fbdd7
license    : Apache-2.0
component  : programming.python
summary    : A package designed to expose cryptographic recipes and primitives to Python developers
description: |
    A package designed to expose cryptographic recipes and primitives to Python developers
builddeps  :
    - pkgconfig(python3)
    - python-cffi
    - python-setuptools
rundeps    :
    - python-asn1
    - python-asn1crypto
    - python-cffi
    - python-enum34
    - python-idna
    - python-ipaddress
    - python-packaging
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
