name       : python-cryptography
version    : 1.2.2
release    : 1
source     :
    - http://pypi.python.org/packages/source/c/cryptography/cryptography-1.2.2.tar.gz : 3f219cb9106d9b737ea9c332c4d15d70ac328f91b59fd9d79f78bdea8f826a67
license    : Apache-2.0
summary    : A package designed to expose cryptographic recipes and primitives to Python developers
description: |
    A package designed to expose cryptographic recipes and primitives to Python developers
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-setuptools
    - python-six
rundeps    :
    - python-cffi
    - python-enum34
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
