name       : python-cryptography
version    : 2.2.1
release    : 11
source     :
    - https://files.pythonhosted.org/packages/source/c/cryptography/cryptography-2.2.1.tar.gz : dddad9d322a3f0867009ff9f25477b8f7c0bdbedf143704b384c9472f11cb2d3
license    : Apache-2.0
component  : programming.python
summary    : A package designed to expose cryptographic recipes and primitives to Python developers
description: |
    A package designed to expose cryptographic recipes and primitives to Python developers
builddeps  :
    - pkgconfig(python3)
    - python-cffi
    - python-setuptools
rundeps    :
    - python-asn1
    - python-asn1crypto
    - python-cffi
    - python-enum34
    - python-idna
    - python-ipaddress
    - python-packaging
    - python-six
build      : |
    %patch -p1 < $pkgfiles/security/cve-2018-10903.patch
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
