name       : python-cryptography
version    : 2.3.1
release    : 12
source     :
    - https://github.com/pyca/cryptography/archive/2.3.1.tar.gz : ff45a7f377d7f0fc79bdd4254b39f17c317ef0e6dc996da6795d5d3fd1718269
license    : Apache-2.0
component  : programming.python
summary    : A package designed to expose cryptographic recipes and primitives to Python developers
description: |
    A package designed to expose cryptographic recipes and primitives to Python developers
builddeps  :
    - pkgconfig(python3)
    - python-cffi
    - python-setuptools
rundeps    :
    - python-asn1
    - python-asn1crypto
    - python-cffi
    - python-enum34
    - python-idna
    - python-ipaddress
    - python-packaging
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
