name       : python-cryptography
version    : 1.7.1
release    : 3
source     :
    - https://pypi.python.org/packages/82/f7/d6dfd7595910a20a563a83a762bf79a253c4df71759c3b228accb3d7e5e4/cryptography-1.7.1.tar.gz : 953fef7d40a49a795f4d955c5ce4338abcec5dea822ed0414ed30348303fdb4c
license    : Apache-2.0
component  : programming.python
summary    : A package designed to expose cryptographic recipes and primitives to Python developers
description: |
    A package designed to expose cryptographic recipes and primitives to Python developers
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-cffi
    - python-cparser
    - python-setuptools
    - python-six
rundeps    :
    - python-cffi
    - python-cparser
    - python-enum34
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
