name       : python-cryptography
version    : 1.5.2
release    : 2
source     :
    - https://pypi.python.org/packages/03/1a/60984cb85cc38c4ebdfca27b32a6df6f1914959d8790f5a349608c78be61/cryptography-1.5.2.tar.gz : eb8875736734e8e870b09be43b17f40472dc189b1c422a952fa8580768204832
license    : Apache-2.0
component  : programming.python
summary    : A package designed to expose cryptographic recipes and primitives to Python developers
description: |
    A package designed to expose cryptographic recipes and primitives to Python developers
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-setuptools
    - python-six
rundeps    :
    - python-cffi
    - python-enum34
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
