name       : python-cryptography
version    : 3.4.8
release    : 23
source     :
    - https://pypi.io/packages/source/c/cryptography/cryptography-3.4.8.tar.gz : 94cc5ed4ceaefcbe5bf38c8fba6a21fc1d365bb8fb826ea1688e3370b2e24a1c
homepage   : https://github.com/pyca/cryptography
license    : Apache-2.0
component  : programming.python
networking : yes
summary    : A package designed to expose cryptographic recipes and primitives to Python developers
description: |
    A package designed to expose cryptographic recipes and primitives to Python developers.
builddeps  :
    - pkgconfig(python3)
    - cargo
    - python-cffi
    - python-setuptools-rust
    - python-cryptography-vectors # check, update this package whenever you update python-cryptography
    - python-hypothesis           # check
    - python-iso8601              # check
    - python-pretend              # check
    - pytest-runner               # check
    - pytest-subtests             # check
    - python-pytz                 # check
rundeps    :
    - python-cffi
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest
